"""Add size to cart_items and sizes to products

Revision ID: 0433e567776d
Revises: 
Create Date: 2025-04-10 00:42:37.941914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0433e567776d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=10), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sizes')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
